export const metadata = {
    title: 'Next.js',
    description: 'Generated by Next.js',
  }
  
  export default function ProductDetailsLayout({ children }) {
    return (
     <>
        {children}
        <h2 style={{backgroundColor:"lightgreen"}}>features products</h2>
     </>
    )
  }
  